# Generated by Django 5.2.11 on 2026-03-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_owner_i_db5cd3_idx',
            old_name='documents_d_owner_i_71cf99_idx',
        ),
    ]
