# Generated by Django 5.2.11 on 2026-03-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicalevent',
            new_name='records_med_owner_i_7eb5fb_idx',
            old_name='records_med_owner_i_0ebfd1_idx',
        ),
        migrations.RenameIndex(
            model_name='medicalevent',
            new_name='records_med_owner_i_b20156_idx',
            old_name='records_med_owner_i_e30629_idx',
        ),
    ]
